version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - "8000:8000"